kind: pipeline
type: kubernetes
name: default

steps:
- name: publish
  image: plugins/kaniko
  settings:
    registry: harbor.mcswain.dev
    repo: harbor.mcswain.dev/library/kitty-chromecast
    tags: ${DRONE_COMMIT_SHA}
    cache: true
    username:
      from_secret: library-username
    password:
      from_secret: library-password
